server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: playwright-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: playwright-e2e
          __path__: /var/log/playwright/execution-*.log
